# Generated by Django 5.1.4 on 2025-01-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0002_emprunt_date_prevu_retour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='date_prevu_retour',
        ),
    ]
