# Generated by Django 5.1.4 on 2024-12-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
    ]
